manifests/base/admin-deployment.yaml
manifests/base/admin-hpa.yaml
manifests/base/api-deployment.yaml
manifests/base/kustomization.yaml
manifests/base/proxy-deployment.yaml
manifests/base/proxy-service.yaml
manifests/base/redis-deployment.yaml
manifests/base/redis-service.yaml
manifests/base/traefik-ingress.yaml
manifests/overlays/eks/aggregated-metrics-reader.yaml
manifests/overlays/eks/auth-delegator.yaml
manifests/overlays/eks/auth-reader.yaml
manifests/overlays/eks/kustomization.yaml
manifests/overlays/eks/metrics-apiservice.yaml
manifests/overlays/eks/metrics-server-deployment.yaml
manifests/overlays/eks/metrics-server-service.yaml
manifests/overlays/eks/resource-reader.yaml

Closes https://github.com/cds-snc/notification-api/issues/513

Metrics, Proxy Demo, and Redis

---

manifests/overlays/eks/celery-deployment-fargate.yaml
manifests/overlays/eks/kustomization.yaml

Fargate config

---

Makefile
README.md
infrastructure/aws/build/acm.tf
infrastructure/aws/build/alb.tf
infrastructure/aws/build/alerts.tf
infrastructure/aws/build/buckets.tf
infrastructure/aws/build/sns.tf

Closes https://github.com/cds-snc/notification-api/issues/565

Added alerts

---

manifests/overlays/eks/kustomization.yaml

Fix image tags

---

README.md
manifests/base/admin-deployment.yaml
manifests/base/api-deployment.yaml
manifests/base/celery-deployment.yaml

Scale more API pods, scale down celery, set resources

Small tweaks

---

manifests/base/admin-hpa.yaml
manifests/base/api-deployment.yaml
manifests/base/celery-deployment.yaml

Tried these on staging and they faired a lot better

More nuanced limits

---

manifests/overlays/eks/kustomization.yaml

We haven't released in a while so this contains a lot of changes:
- Pinpoint client in API
- New flow to add an inbound SMS number in Admin 
- Lots of french translations
- Clean up of template/branding code
- Un-fix the SES sending region
- Bring back new relic (on staging)
- Feature to read local jinja files
- Security updates
- John's code to cache homepage stats
- Move very static assets to S3
- Add redis integration

Updated to latest admin and api

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Translate missing text on template history page (#556)](https://github.com/cds-snc/notification-admin/commit/7045d3144c5852554d1c31e253e18d96e64dfc36)
- [bump reqs to pick up new utils version (#555)](https://github.com/cds-snc/notification-admin/commit/982578c0e1159c2e04d3e7af839695bad929676c)
- [[Snyk] Upgrade dayjs from 1.8.25 to 1.8.26 (#544)](https://github.com/cds-snc/notification-admin/commit/d6fa5d25c8cabd0a75911781edda883d5c333adb)
- [[Snyk] Upgrade moment from 2.24.0 to 2.25.0 (#547)](https://github.com/cds-snc/notification-admin/commit/4996fe7592b0bd5aef02ac339f53e32bb2161482)
- [Add platform admin setting for service message limit (#549)](https://github.com/cds-snc/notification-admin/commit/4a64ed254b60548d52cc24e7658ed9158f0c0ec3)
- [Translated the jobs page …

[AUTO-PR] Automatically generated new release 2020-05-25T20:42:51.266Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [fix: upgrade sweetalert2 from 9.10.12 to 9.10.13 (#579)](https://github.com/cds-snc/notification-admin/commit/03cf5d7e4856f5a89f81db07b7c054cd76a5a970)
- [added translation (#583)](https://github.com/cds-snc/notification-admin/commit/538a8bb2f71928c35453de5aae57450073fd274c)
- [added the new translation (#582)](https://github.com/cds-snc/notification-admin/commit/ab65ef5a15130885a7c191c1da58cc35e5ee8308)
- [Bulk send from S3 (#550)](https://github.com/cds-snc/notification-admin/commit/f134797ce2525a4fbf07f2862ce0e098ad53b722)
- [Verification link translation (#576)](https://github.com/cds-snc/notification-admin/commit/c7b5ac178906386a5b15ca4684c9775ae27e0502)
- [Delete URL was incorrect (#577)](https://github.com/cds-snc/notification-admin/commit/d624c0bfa465058702a721e5ee3459a4 …

[AUTO-PR] Automatically generated new release 2020-06-03T14:59:02.191Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [remove pricing link from homepage (#621)](https://github.com/cds-snc/notification-admin/commit/5e983a69c5f1a13905e5f14e1d3335d003d27d51)
- [Translate error messages and wrap strings coming from the API (#624)](https://github.com/cds-snc/notification-admin/commit/25ea964347f490c414e94c7197468e9a06d0c0d3)
- [return 400 rather than 500 for newline in params (#623)](https://github.com/cds-snc/notification-admin/commit/70ab52d033c8806e838b6a4a915652156dbbee20)
- [translate landmark aria-labels (#622)](https://github.com/cds-snc/notification-admin/commit/3129f41273b5f41e76a2613f7afaa36456552e67)
- [add translation (#619)](https://github.com/cds-snc/notification-admin/commit/ee9d4f88e45bb5b7e3f3b6c730f14b1ef1327b30)
- [skip template tutorial …

[AUTO-PR] Automatically generated new release 2020-06-22T15:09:16.879Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Fix bad redirect with fido2 key (#630)](https://github.com/cds-snc/notification-admin/commit/4d557e66bad9f514585e339f0ac38e7b12619564) 
API:

[AUTO-PR] Automatically generated new release 2020-06-22T20:23:10.193Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [translate skip link text (#670)](https://github.com/cds-snc/notification-admin/commit/b4ca48cfecd7778748ba0fc01d707d9075a51fec)
- [sort files with most recent on top (#673)](https://github.com/cds-snc/notification-admin/commit/dca21d1ab3afc007b6514e96816af84a8ac56b3c)
- [remove trial-mode page and related links/content (#663)](https://github.com/cds-snc/notification-admin/commit/993150d9667aa58252307c90fbd8a0c89637d279)
- [Update terms of use page content (#664)](https://github.com/cds-snc/notification-admin/commit/df2cbd595e5290e595d0a4297804b14bfe865ac2)
- [fresh npm install to fix dep vulnerabilities (#661)](https://github.com/cds-snc/notification-admin/commit/fbc7347da54389c3cb401f9714cbd5fae32f39ea)
- [[Snyk] Security upgrade rsa from 3.4.2 to 4.1 …

[AUTO-PR] Automatically generated new release 2020-07-21T16:07:57.426Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Reset failed login attempts when unblocking users (#759)](https://github.com/cds-snc/notification-admin/commit/7b7eb7729f6d78ea04a73960356c64008f3d7662)
- [Missing space in sentence (#755)](https://github.com/cds-snc/notification-admin/commit/51ce1e1f14722fe74290e0deb9520d61c5832015)
- [Remove extra character in template (#754)](https://github.com/cds-snc/notification-admin/commit/00452150b54043b2a6147aaea5de3e81ec2f5f7c)
- [Users switch branding (#712)](https://github.com/cds-snc/notification-admin/commit/eeff101b12ae501f01ae53290cdeb3656882aead)
- [fix: package.json & package-lock.json to reduce vulnerabilities (#715)](https://github.com/cds-snc/notification-admin/commit/bd8034241d28d17c5f2355eca64e9ffb55d3018f)
- [Sprintly dependency bump …

[AUTO-PR] Automatically generated new release 2020-09-16T14:10:43.660Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Build the correct endpoint for the feedback confirmation page (#765)](https://github.com/cds-snc/notification-admin/commit/ed7f1ea1c973f759b95f313be972b1a353f851f3) 
API: 
- [Make account changes email bilingual (#1128)](https://github.com/cds-snc/notification-api/commit/ca76a1653267f4d64c84b2093bbe31a3cd4c2abf)

[AUTO-PR] Automatically generated new release 2020-09-17T21:48:30.396Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Bump dependencies on 2020-10-05 (#782)](https://github.com/cds-snc/notification-admin/commit/0ecc2773bade985c51a82ed01c8c316a992d07f7)
- [Import tailwind (#783)](https://github.com/cds-snc/notification-admin/commit/73498a76f13e56cb6178b08cb5a74e5e9678e0e1)
- [Translate placeholders in template (#771)](https://github.com/cds-snc/notification-admin/commit/9c198d4f8aa157d0cd7090675f746d39733bd612)
- [Adding a new docker compose file to help reproduce prod env. (#776)](https://github.com/cds-snc/notification-admin/commit/508d48b38d8b267affeeefe5a592839aed8c9c16)
- [Missing French in service settings and 'Receive text message' page (#778)](https://github.com/cds-snc/notification-admin/commit/86e36297a2f5ea6dde821b10bff40514943a3d5f)
- [Add missing space …

[AUTO-PR] Automatically generated new release 2020-10-08T12:35:00.048Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Upgrade Flask-Login (#790)](https://github.com/cds-snc/notification-admin/commit/ad845ba472979cf1ec899ee4c93ba605be8932fd)
- [Remove blocked attribute on non User models (#789)](https://github.com/cds-snc/notification-admin/commit/ee6566836e61157ff21ff1c2d9885c459f0f9aba)
- [Additional tests and cleanup for permissions (#788)](https://github.com/cds-snc/notification-admin/commit/5352d68698836c36809631ebdfd02c08be274086)
- [Cache npm and pip on GitHub Actions (#787)](https://github.com/cds-snc/notification-admin/commit/9e8ed0ca02e80198968e7ee1067092737ff9dade)
- [Additional tests for security keys (#785)](https://github.com/cds-snc/notification-admin/commit/12fe4a68721abecac0d58f82dd98864c3bd68fe0)
- [Remove header.css and replace with tailwind styles …

[AUTO-PR] Automatically generated new release 2020-10-14T20:23:03.089Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Remove banner.scss and port to tailwind. Also upgrade tailwind to current version (#798)](https://github.com/cds-snc/notification-admin/commit/3db46514708c1169a36602cbf3bbe178c001a926)
- [Adding a service to an org cleans orgs cache (#796)](https://github.com/cds-snc/notification-admin/commit/c19471e06692ce914da0beaefccac6efbf78b43f)
- [Bump utils to 43.1.0 (#797)](https://github.com/cds-snc/notification-admin/commit/3f76ecb4b500c2820aab0b59c4a187304e87c653)
- [Retry failed requests to the Notify API (#793)](https://github.com/cds-snc/notification-admin/commit/840e29cc3c0deecef83a7bdb4fd5f63892e087b2)
- [Low hanging fruit CSS cleanup (#794)](https://github.com/cds-snc/notification-admin/commit/6b0264e44e121cc0927ee3017aeaa9baea1cd503)
- [Upgrade WTForms …

[AUTO-PR] Automatically generated new release 2020-10-22T14:06:48.201Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Bump utils to 43.1.1 (#800)](https://github.com/cds-snc/notification-admin/commit/c84a7b7f509d65843aeebd047927dd5dbe8ad9fc) 
API: 
- [Bump utils to 43.1.1 (#1161)](https://github.com/cds-snc/notification-api/commit/d8e9c6b4cd2c4263c3c61dcec4aee12e39643506)

[AUTO-PR] Automatically generated new release 2020-10-22T17:09:56.933Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [revert main.min.js (#801)](https://github.com/cds-snc/notification-admin/commit/be83f3521ce61ed5a757ad04155ce4a3d18b889c) 
API:

[AUTO-PR] Automatically generated new release 2020-10-22T20:01:04.431Z

---

manifests/overlays/eks/kustomization.yaml

⚠️ There was a merged pull request in [notification-staging-tf](https://github.com/cds-snc/notification-staging-tf) since last deploy in production! Check first that you don't need to change the infrastructure here. 
ADMIN: 
- [fix: upgrade diff-dom from 4.2.0 to 4.2.1 (#795)](https://github.com/cds-snc/notification-admin/commit/f8cd6824b17b8f819a20fa378b3d80e18303c2b1)
- [Css components (#804)](https://github.com/cds-snc/notification-admin/commit/7df86d972f4850d4d1f57fe2ceae6ab3fc114d86)
- [Fix method to get the real IP address (#799)](https://github.com/cds-snc/notification-admin/commit/56c00e1e5ca84699230654d387b2f4cc07784924)
- [Update French translation on homepage (#802)](https://github.com/cds-snc/notification-admin/commit/183e07587634e87ba7ba2b0cdb8b100b38ae3c16)
- [Webpack fix …

[AUTO-PR] Automatically generated new release 2020-10-28T15:08:25.451Z

---

manifests/overlays/eks/kustomization.yaml

⚠️ There was a merged pull request in [notification-staging-tf](https://github.com/cds-snc/notification-staging-tf) since last deploy in production! Check first that you don't need to change the infrastructure here. 
ADMIN: 
- [Upgrade Python dependencies (#812)](https://github.com/cds-snc/notification-admin/commit/84e181762bf8aa74c08e60649821e7672d617550)
- [Remove cds_template_jinja dependency (#811)](https://github.com/cds-snc/notification-admin/commit/a15d2d0e150064bfb89d162844383e95ef2e00fe)
- [add npm run tailwind command (#809)](https://github.com/cds-snc/notification-admin/commit/e8a2fbacede2d6dcac17da1c7ae724873568dcf6)
- [fix css glitch on platform admin page (#808)](https://github.com/cds-snc/notification-admin/commit/05d0c5bb47b8f1d30b72e2619b066c631291c518)
- [Css components …

[AUTO-PR] Automatically generated new release 2020-11-04T18:13:46.640Z

---

manifests/overlays/eks/kustomization.yaml

⚠️ There was a merged pull request in [notification-staging-tf](https://github.com/cds-snc/notification-staging-tf) since last deploy in production! Check first that you don't need to change the infrastructure here. 
ADMIN: 
- [Remove inbound message / conversation views (#814)](https://github.com/cds-snc/notification-admin/commit/d7c4c797eed6075a75e3c22ccd6227f471bbc622) 
API: 
- [No HTTP callbacks for SES (#1171)](https://github.com/cds-snc/notification-api/commit/d11c9a5c527e204915ccbdf0baeca0828b3ce72a)
- [Celery: register process_sns_receipts_tasks (#1170)](https://github.com/cds-snc/notification-api/commit/cc7e420debccd27b7882821f1153516123a47334)
- [Celery task for SNS callbacks (#1169)](https://github.com/cds-snc/notification-api/commit/5e736fe1240b2cc479435394b509fd5f410ace31)

[AUTO-PR] Automatically generated new release 2020-11-06T15:58:26.936Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Port message css (sms and email) files (#817)](https://github.com/cds-snc/notification-admin/commit/f0e2935f633207bf3af9205d774a3285bbdb7680) 
API: 
- [Send methods stats by service endpoint (#1174)](https://github.com/cds-snc/notification-api/commit/deff35ed8622d8130755d8e483675666ed8492c9)
- [Notification stats for trial services (#1173)](https://github.com/cds-snc/notification-api/commit/b5e0c25a5e7354f45ee688522e07d3906f0b7369)

[AUTO-PR] Automatically generated new release 2020-11-12T14:08:23.860Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Add trial accounts report (#818)](https://github.com/cds-snc/notification-admin/commit/6cb3e403d5d15bce39ddb4751339274da0aaea7f) 
API: 
- [Add failed to NOTIFICATION_STATUS_TYPES_FAILED (#1175)](https://github.com/cds-snc/notification-api/commit/258dd04af9d5aac983bfe50fc81fad8ed2d909f7)

[AUTO-PR] Automatically generated new release 2020-11-12T19:03:49.720Z

---

manifests/overlays/eks/kustomization.yaml

ADMIN: 
- [Activity dashboard (#810)](https://github.com/cds-snc/notification-admin/commit/33f5819a91bc853114234cea101ef44b6c5ae88d) by Antoine Augusti
- [Update docker.yaml (#821)](https://github.com/cds-snc/notification-admin/commit/a918e87192299d612c65abcf77ab01669a961c91) by Max Neuvians
- [Report: send method stats by service (#819)](https://github.com/cds-snc/notification-admin/commit/0376fc62713dfb6c9408cf9dad30cb24341cbde1) by Antoine Augusti
- [Selection elements CSS (#820)](https://github.com/cds-snc/notification-admin/commit/9f30fc7cf9087595138f89cd27221001a880ba4e) by Bethany Dunfield 
API: 
- [Setup VSCode devcontainer for notification-api (#1177)](https://github.com/cds-snc/notification-api/commit/823c3f0b4cb55d2d83a3e895e18f484a3adc6c8e) by Jimmy Royer
- [fix: repaired the …

[AUTO-PR] Automatically generated new release 2020-11-18T21:46:19.436Z

---

.github/PULL_REQUEST_TEMPLATE.md

That notification isn't necessary anymore.

fix: PR Template: Removed step around notification to sre-team 
